required-players: 1
countdown-seconds: 30
blockgame-blocks-to-break-count: 4
pvpgame-player-kill-count: 4

world-filepath: 'C:\Users\lfind\OneDrive\Desktop\multiMini\'
world-source-arenas: 'C:\Users\lfind\OneDrive\Desktop\multiMini\'

hanger-countdown-seconds: 180
firstboss-countdown-seconds: 600
parkour_1-seconds: 600
maze-seconds: 240
boss_2-seconds: 720
parkour_2-seconds: 480
teleportation-seconds: 300
leave_the_dungeon-seconds: 120
dungeon_cooldown-seconds: 300

blockgameNpc:
  x: 217.01
  y: 54.000
  z: -10.32
  yaw: 0
  pitch: 0

pvpNpc:
  x: 224.126
  y: 54.000
  z: -10.32
  yaw: 0
  pitch: 0

stronghold:
  world: 'arena4'
  x: 226.968
  y: 53.000
  z: -5.700
  yaw: 0
  pitch: 0

lobby-spawn:
  world: 'world'
  x: 220
  y: 53
  z: 4.87
  yaw: 180
  pitch: 0

arenas:
  '0':
    game: 'BLOCK'
    world: 'arena1'
    x: 202
    y: 4
    z: 3.055
    pitch: 0
    yaw: -90

  '1':
    game: 'PVP'
    world: 'arena2'
    x: 202
    y: 4
    z: 3.055
    pitch: 0
    yaw: -90

  '2':
    game: 'DUNGEON'
    world: 'arena3'
    x: -27
    y: 79
    z: 65
    pitch: 0
    yaw: 0

  '3':
    game: 'STRONGHOLD'
    world: 'arena4'
    x: 33
    y: 87
    z: 483
    pitch: 0
    yaw: 93

# Cod Stronghold
cod-required-players: 2
game-time-seconds: 300
kills-to-win: 2
waiting:
  world: 'arena4'
  x: 33
  y: 87
  z: 483
  pitch: 0
  yaw: 93
spawn-blue:
  '0':
    world: 'arena4'
    x: -160
    y: 85
    z: 493
    pitch: 0
    yaw: -41
  '1':
    world: 'arena4'
    x: -159
    y: 80
    z: 480
    pitch: 0
    yaw: -37
  '2':
    world: 'arena4'
    x: -116
    y: 92
    z: 464
    pitch: 0
    yaw: -29
  '3':
    world: 'arena4'
    x: -69
    y: 88
    z: 456
    pitch: 0
    yaw: -31
  '4':
    world: 'arena4'
    x: -105
    y: 85
    z: 498
    pitch: 0
    yaw: 35
spawn-red:
  '0':
    world: 'arena4'
    x: -133
    y: 82
    z: 546
    pitch: 0
    yaw: -90
  '1':
    world: 'arena4'
    x: -32
    y: 84
    z: 510
    pitch: 0
    yaw: 135
  '2':
    world: 'arena4'
    x: -63
    y: 87
    z: 533
    pitch: 0
    yaw: 57
  '3':
    world: 'arena4'
    x: -51
    y: 106
    z: 534
    pitch: 0
    yaw: 148
  '4':
    world: 'arena4'
    x: -132
    y: 82
    z: 544
    pitch: 0
    yaw: 180