required-players: 1
countdown-seconds: 10
lobby-spawn:
  world: 'world'
  x: -119
  y: 73
  z: -91
  yaw: 12
  pitch: 9.3

arenas:
  '0':
    world: 'world'
    x: 181
    y: 77
    z: 391
    pitch: 0
    yaw: 0

  '1':
    world: 'world'
    x: 181
    y: 77
    z: 391
    pitch: 0
    yaw: 0
