# minimum player count for all mini games:
required-players-block-game: 1
required-players-stronghold: 2
required-players-wak_a_block: 1
required-players-pvp-vs: 2
required-players-dungeon: 1
required-players-deadSpace: 1

# countdown in seconds when minimum player count is met this is the countdown before game starts
countdown-seconds: 10

# specific game counts to win game   NOTE: cod stronghold has its own setting for kills to win in its section
blockgame-blocks-to-break-count: 4
pvpgame-player-kill-count: 2
wak_a_block_win_count: 2

#Wak_A_Block enemies count
enemies_count: 1

# if you change main-world-name you also have to change lobby-spawn 'world'
main-world-name: 'world'

# set the paths to game maps.
# world-filepath:  is where your game maps are that are in use (users playing on)
# world-source-arenas: this is path to reset maps back to original (when game is finished)
world-filepath: 'C:\Users\lfind\OneDrive\Desktop\multiMini\'
world-source-arenas: 'C:\Users\lfind\OneDrive\Desktop\multiMini\'

# lobby for game choice:
lobby-spawn:
  world: 'world'
  x: 220
  y: 53
  z: 4.87
  yaw: 180
  pitch: 0

# specific spawn for games waiting to start
arenas:
  '0':
    game: 'BLOCK'
    world: 'arena1'
    x: 202
    y: 4
    z: 3.055
    pitch: 0
    yaw: -90

  '1':
    game: 'PVP'
    world: 'arena2'
    x: 198.440
    y: 10
    z: 227.023
    pitch: 0
    yaw: -90

  '2':
    game: 'WAK_A_BLOCK'
    world: 'arena3'
    x: 205.797
    y: 87
    z: 226.736
    pitch: 0
    yaw: -90

  '3':
    game: 'STRONGHOLD'
    world: 'arena4'
    x: 33
    y: 87
    z: 483
    pitch: 0
    yaw: 93

  '4':
    game: 'DUNGEON'
    world: 'arena5'
    x: -27
    y: 79
    z: 65
    pitch: 0
    yaw: 0

  '5':
    game: 'DEADSPACE'
    world: 'arena6'
    x: 1739.177
    y: 87.000
    z: -49.566
    pitch: 0
    yaw: -90

# pvp one on one extra game live spawns
pvp-1on1:
  '0':
    world: 'arena2'
    x: 182
    y: 9.0
    z: 216.88
    pitch: 0
    yaw: -50
  '1':
    world: 'arena2'
    x: 176.902
    y: 9.0
    z: 227.474
    pitch: 0
    yaw: -90
  '2':
    world: 'arena2'
    x: 198.505
    y: 9.0
    z: 247.696
    pitch: 0
    yaw: 180
  '3':
    world: 'arena2'
    x: 221.244
    y: 9.0
    z: 227.776
    pitch: 0
    yaw: 90

# total game time regardless of kills
game-time-block: 300
game-time-pvp: 300
game-time-wak: 300
game-time-cod: 300

# Cod Stronghold: game parameters
# number of kills a team needs to win the game
kills-to-win: 2

# multiple spawn for blue team
spawn-blue:
  '0':
    world: 'arena4'
    x: -160
    y: 85
    z: 493
    pitch: 0
    yaw: -41
  '1':
    world: 'arena4'
    x: -159
    y: 80
    z: 480
    pitch: 0
    yaw: -37
  '2':
    world: 'arena4'
    x: -116
    y: 92
    z: 464
    pitch: 0
    yaw: -29
  '3':
    world: 'arena4'
    x: -69
    y: 88
    z: 456
    pitch: 0
    yaw: -31
  '4':
    world: 'arena4'
    x: -105
    y: 85
    z: 498
    pitch: 0
    yaw: 35

# multiple spawn for red team
spawn-red:
  '0':
    world: 'arena4'
    x: -133
    y: 82
    z: 546
    pitch: 0
    yaw: -90
  '1':
    world: 'arena4'
    x: -32
    y: 84
    z: 510
    pitch: 0
    yaw: 135
  '2':
    world: 'arena4'
    x: -63
    y: 87
    z: 533
    pitch: 0
    yaw: 57
  '3':
    world: 'arena4'
    x: -51
    y: 106
    z: 534
    pitch: 0
    yaw: 148
  '4':
    world: 'arena4'
    x: -132
    y: 82
    z: 544
    pitch: 0
    yaw: 180

# dungeon room times in seconds
maxPlayer_count-seconds: 24
entrance-countdown-seconds: 90
hanger-countdown-seconds: 180
firstboss-countdown-seconds: 600
parkour_1-seconds: 600
maze-seconds: 240
boss_2-seconds: 720
parkour_2-seconds: 480
teleportation-seconds: 300
leave_the_dungeon-seconds: 120
dungeon_cooldown-seconds: 300

